ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false            # 如果只在平面上定位
    publish_tf: false
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # 使用来自轮式编码器或激光雷达的里程计数据
    odom0: /lio_sam/mapping/odometry
    odom0_config: [true,  true, true,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: false

    twist0: /fix_velocity
    twist0_config: [false, false, false,
                    false, false, false,
                    true,  true,  false,
                    false, false, false,
                    false, false, false]
    twist0_differential: false
