navsat_transform_node:
  ros__parameters:
    frequency: 30.0
    use_odometry_yaw: true
    #yaw_offset: 0.314159
    imu_topic: ""
    zero_altitude: false
    broadcast_cartesian_transform: false
    publish_filtered_gps: true
    wait_for_datum: false
    transform_timeout: 0.0
