pointcloud_to_laserscan:
  ros__parameters:
    target_frame: livox_frame
    min_height: 0.0
    max_height: 1.5
    angle_min: -3.14159274101
    angle_max: 3.14159274101    #3.14159274101
    angle_increment: 0.005
    scan_time: 0.1
    range_min: 0.5
    range_max: 70.0
    concurrency_level: 0
